services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ports:
      - "3000:3000"
      - "4200:4200"
      - "5173:5173"
      - "5555:5555"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
